package com.qaprism.ai.service;

import com.qaprism.ai.util.PromptBuilder;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

@Slf4j
@Service
public class AnalysisService {

    private final OllamaService ollamaService;

    public AnalysisService(
            OllamaService ollamaService) {

        this.ollamaService =
                ollamaService;
    }

    public String generateArtifact(
            String prdContent,
            String action) {

        long startTime =
                System.currentTimeMillis();

        try {

            log.info(
                    "========================================");

            log.info(
                    "Generating Artifact : {}",
                    action);

            log.info(
                    "PRD Length : {} Characters",
                    prdContent.length());

            log.info(
                    "Building Prompt");

            String prompt =
                    PromptBuilder.buildArtifactPrompt(
                            prdContent,
                            action);

            log.info(
                    "Prompt Generated Successfully");

            log.info(
                    "Prompt Length : {} Characters",
                    prompt.length());

            log.info(
                    "========================================");

            log.info(
                    "PROMPT SENT TO OLLAMA");

            log.info(
                    "\n{}",
                    prompt);

            log.info(
                    "========================================");

            log.info(
                    "Sending Request To Ollama");

            String response =
                    ollamaService.generateResponse(
                            prompt);

            log.info(
                    "Response Received From Ollama");

            log.info(
                    "Response Length : {} Characters",
                    response.length());

            log.info(
                    "========================================");

            log.info(
                    "RAW RESPONSE FROM OLLAMA");

            log.info(
                    "\n{}",
                    response);

            log.info(
                    "========================================");

            if (response == null ||
                    response.isBlank()) {

                return """
                    No response generated by model.

                    Possible causes:

                    - Ollama model not running
                    - Model timeout
                    - Prompt too large
                    - Invalid response format
                    """;
            }

            long endTime =
                    System.currentTimeMillis();

            log.info(
                    "Artifact Generated In {} Seconds",
                    (endTime - startTime) / 1000);

            log.info(
                    "========================================");

            return response;

        } catch (Exception exception) {

            log.error(
                    "Failed To Generate Artifact : {}",
                    action,
                    exception);

            return """
                Generation Failed

                Error:
                """
                    + exception.getMessage();
        }
    }


}
