#################################################
# APPLICATION
#################################################

spring.application.name=QA Prism AI

server.port=8080

#################################################
# THYMELEAF
#################################################

spring.thymeleaf.cache=false

#################################################
# FILE UPLOAD
#################################################

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=20MB

spring.servlet.multipart.max-request-size=20MB

#################################################
# OLLAMA
#################################################

ollama.url=http://localhost:11434/api/generate

ollama.model=qwen2.5:3b

#################################################
# EXPORT REPORTS
#################################################

report.path=reports

#################################################
# LOGGING
#################################################

logging.level.root=INFO

logging.level.com.qaprism.ai=DEBUG